volumes:
  langgraph-data:
    driver: local
services:
  langgraph-redis:
    image: docker.io/redis:6
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5
  langgraph-postgres:
    image: docker.io/postgres:16
    ports:
      - "8122:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - langgraph-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
  langgraph-api:
    image: gemini-fullstack-langgraph
    ports:
      - "8123:8000"
    depends_on:
      langgraph-redis:
        condition: service_healthy
      langgraph-postgres:
        condition: service_healthy
    environment:
      # API Provider Selection (gemini or openai)
      API_PROVIDER: gemini
      
      # API Keys (set the one corresponding to your API_PROVIDER choice)
      GEMINI_API_KEY: your-gemini-api-key-here
      # OPENAI_API_KEY: your-openai-api-key-here
      
      # Other settings
      LANGSMITH_API_KEY: your-langsmith-api-key-here
      HTTP_PROXY: http://host.docker.internal:7893
      HTTPS_PROXY: http://host.docker.internal:7893
      REDIS_URI: redis://langgraph-redis:6379
      POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
